"""Sieve script body generator (RFC 5228) for the email-processing-hand.

Converts in-memory ``sender_rules`` into a Sieve script that the agent
uploads via rustymail's ``sieve_put_script`` MCP tool. The upload
orchestration (check → put → set-active) lives in the system prompt
Phase 7 — this module is the pure body-builder.

## Which buckets compile to Sieve?

Only buckets whose action is purely server-side execute as Sieve rules:

* ``Filter``        → ``fileinto`` (+ ``addflag "\\Seen"`` by default)
* ``Blacklist``     → ``discard``
* ``UnsubAndBlock`` → ``discard`` (after the unsubscribe submission)

Buckets that need post-classification logic (digest assembly, calendar
conflict checks, Slack alerts) stay client-side. They get a comment in
the generated script so an operator reading it sees them, but no
matching ``if`` block fires.
"""

from __future__ import annotations

import re
from typing import Any, Iterable

# Buckets we know how to compile into a Sieve rule.
_PUSHABLE_BUCKETS = {"Filter", "Blacklist", "UnsubAndBlock"}

_REQUIRES = ('"fileinto"', '"imap4flags"', '"envelope"', '"regex"')

# RFC 5804 §1.6 — control chars + U+2028/U+2029 are forbidden in sieve
# names, but we apply the same restriction to header values we emit
# verbatim into the script as a defense-in-depth measure.
_BAD_NAME_CHAR = re.compile(r"[\x00-\x1f\x7f-\x9f  ]")


def build_script_body(
    rules: Iterable[dict[str, Any]],
    *,
    generated_at: str | None = None,
) -> str:
    """Render the full Sieve script. Convenience wrapper that drops the
    summary side-channel — callers who want it use :func:`build_with_summary`.
    """
    body, _ = build_with_summary(rules, generated_at=generated_at)
    return body


def build_with_summary(
    rules: Iterable[dict[str, Any]],
    *,
    generated_at: str | None = None,
) -> tuple[str, dict[str, Any]]:
    """Render the script body AND return a summary of what was
    emitted / skipped, with reasons. The summary is what the agent
    surfaces to the operator after a Sieve regen.
    """
    rules = sorted(rules, key=lambda r: r.get("rule_id", ""))
    emitted_count = 0
    skipped_count = 0
    skipped_buckets: list[str] = []
    skip_reasons: list[str] = []

    lines: list[str] = []
    lines.append(f"require [{', '.join(_REQUIRES)}];\n")
    lines.append("# ─── Hand-managed rules ─── DO NOT EDIT BY HAND")
    lines.append("# This script is regenerated by openfang email-processing-hand.")
    if generated_at:
        lines.append(f"# Last updated: {generated_at}")
    lines.append(f"# Rule count: {len(rules)}\n")

    for rule in rules:
        block, skip_reason = _render_rule(rule)
        if block:
            lines.extend(block)
            lines.append("")
            emitted_count += 1
        else:
            skipped_count += 1
            bucket = rule.get("bucket", "?")
            if bucket not in skipped_buckets:
                skipped_buckets.append(bucket)
            if skip_reason:
                skip_reasons.append(f"{rule.get('rule_id','?')}: {skip_reason}")
            # Still emit a comment so an operator can see the rule
            # exists without acting on it from the script.
            lines.append(f"# {rule.get('rule_id', '?')} ({bucket}: {skip_reason})")
            lines.append("")

    summary = {
        "emitted_count": emitted_count,
        "skipped_count": skipped_count,
        "skipped_buckets": skipped_buckets,
        "skip_reasons": skip_reasons,
    }
    return "\n".join(lines).rstrip() + "\n", summary


def build_summary(rules: Iterable[dict[str, Any]]) -> dict[str, Any]:
    """Compute the summary without rendering the body."""
    _, summary = build_with_summary(rules)
    return summary


def _render_rule(rule: dict[str, Any]) -> tuple[list[str] | None, str]:
    """Render one rule into a block of Sieve lines, or return
    ``(None, reason)`` when the rule isn't pushable."""
    bucket = rule.get("bucket")
    if bucket not in _PUSHABLE_BUCKETS:
        return None, f"bucket {bucket} not server-side"

    scope = rule.get("scope")
    value = rule.get("value") or ""
    if not value:
        return None, "empty rule value"
    if _BAD_NAME_CHAR.search(value):
        return None, "invalid control characters in rule value"
    if scope not in ("sender", "domain"):
        return None, f"scope {scope!r} not Sieve-pushable"

    quoted_value = _quote(value)

    if bucket == "Filter":
        folder = (rule.get("options") or {}).get("folder")
        if not folder:
            return None, "Filter rule missing options.folder"
        if _BAD_NAME_CHAR.search(folder):
            return None, "invalid control characters in folder name"
        match = (
            f'address :is "from" {quoted_value}'
            if scope == "sender"
            else f'address :is :domain "from" {quoted_value}'
        )
        block = [
            f"# {rule.get('rule_id','?')} ({bucket}: {scope}={value} → {folder})",
            f"if {match} {{",
            f'    fileinto {_quote(folder)};',
        ]
        if (rule.get("options") or {}).get("mark_seen", True):
            block.append('    addflag "\\\\Seen";')
        block.append("    stop;")
        block.append("}")
        return block, ""

    # Blacklist + UnsubAndBlock — discard outcome, differing only in
    # how the user got there. The Sieve rule is the same.
    if scope == "sender":
        match = f'address :is "from" {quoted_value}'
    else:
        # Domain blacklists use envelope :domain so internal forwarder
        # bypass via Reply-To headers doesn't defeat the rule.
        match = f'envelope :domain "from" {quoted_value}'

    block = [
        f"# {rule.get('rule_id','?')} ({bucket}: {scope}={value})",
        f"if {match} {{",
        "    discard;",
        "    stop;",
        "}",
    ]
    return block, ""


def _quote(s: str) -> str:
    """RFC 5228 §2.4.2 quoted-string: escape ``\\`` and ``"`` (in that order)."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
